---
categories          : [Produktivität und Terminal anpassen]
description         : 'Das Terminal lässt sich auf vielfältige Weise individualisieren und verbessern, um die Produktivität weiter nach oben zu schrauben.'
---
= Terminal Design – Farben, Schrift, Extras
:description: 'Das Terminal lässt sich auf vielfältige Weise individualisieren und verbessern, um die Produktivität weiter nach oben zu schrauben.'

[.lead]
Das Terminal lässt sich auf vielfältige Weise individualisieren und verbessern, um die Produktivität weiter nach oben zu schrauben.


== Terminal Design: Farben, Schrift, Extras

Das Terminal lässt sich auf vielfältige Weise individualisieren und verbessern, um die Produktivität weiter nach oben zu schrauben.




== Farbschemata ändern

Die Farbschemata für das Terminal ändert man über CMD + , bzw. über das
Menü __Terminal › Einstellungen › Einstellungen__. Um ein neues
Farbschemata samt Typografieeinstellungen als Standard festzulegen,
klickt man unten links auf __Standard__. Spannende Farbschemata sind
z.B. diese hier:

* http://ethanschoonover.com/solarized[Solarized]
* https://github.com/chriskempson/tomorrow-theme/blob/master/OS%20X%20Terminal/Tomorrow%20Night.terminal[Tomorrow
Night (Terminal Version)]

Um die obigen Farbschemata abzuspeichern, geht man wie folgt vor:

1.  Datei herunterladen, die auf `.terminal` endet.
2.  In einem Ordner abspeichern (wo man es bei Bedarf wiederfindet) und
dann Doppelklicken.
3.  Eventuell muss man die Sicherheitseinstellungen des Rechners kurz
für die Installation außer Kraft setzen.
4.  Nachdem sich das Terminal-Fenster mit dem neuen Farbschemata
geöffnet hat, öffnet man die Einstellungen (siehe oben).
5.  Ein Klick auf _Standard_ macht es zum neuen Standardfarbschemata.
