---
categories          : [Ordner und Dateien]
description         : 'Jede Datei und jeder Ordner verfügt über Dateirechte. Wie Dateirechte funktioneren und wie Du Sie mit chmod änderst erklärt dieses Kapitel.'
---
= chmod: Dateirechte verstehen und ändern
:description: Jede Datei und jeder Ordner verfügt über Dateirechte. Wie Dateirechte funktioneren und wie Du Sie mit chmod änderst erklärt dieses Kapitel.

[.lead]
Jede Datei und jeder Ordner verfügt über Dateirechte. Mit dem Befehl `chmod` lassen sich die Rechte leicht ändern, wenn man das System verstanden hat. Und so geht's…

Dateirechte geben Benutzern verschiedene Arten von Berechtigungen zum Lesen, Schreiben und ausführen von Dateien. Zum Beispiel ist es möglich, nur Lesezugriff auf Dateien und Ordner zu setzen, damit diese nicht versehentlich geändert oder gelöscht werden können. Du kannst über die Dateirechte sogar alle Berechtigungen für einen bestimmten Benutzer löschen, damit die Datei noch nicht einmal geöffnet werden kann (obwohl sie noch im Finder sichtbar ist).


Mit dem Befehl CHMOD, englisch f+r _change mode_ – setzt man im UNIX Umfeld Lese-, Schreib- und Ausführungsrechte von Dateien und Verzeichnissen. Spätestens, wenn man eine Website auf einem Server betreut, stolpert man früher oder später über das Thema Dateireichte, da meistens UNIX bzw. Linux Betriebssysteme für das Website-Hosting eingesetzt werden.

== Übersichtstabelle: CHMOD Rechte-System

.CHMOD Rechte-System
[cols="5*", options="header"]
|===

|Zugriffsrecht
|
|
|Oktal
|Bedeutung

|*Eigentümer*
|*Gruppe*
|*Andere*
|
|

|rwx
|rwx
|rwx
|777
|Lesbar, schreibbar und ausführbar für alle Benutzer.

|rwx
|rwx
|r-x
|775
|Wie 1., aber ohne Schreibrecht für andere Benutzer (z.B. bei PHP-Skript).

|rwx
|r-x
|r-x
|755
|Wie 1., aber ohne Schreibrecht für andere Benutzer und Benutzer der eigenen Gruppe.

|rw-
|rw-
|rw-
|666
|Alle Benutzer dürfen lesen und schreiben. +

|rw-
|rw-
|r--
|664
|Typischer Standardwert für neue Dateien: Lesbar für alle Benutzer, nicht schreibbar und ausführbar für andere Benutzer.

|rw-
|rw-
|---
|660
|Der Dateibesitzer und die Gruppe darf die Datei lesen und schreiben, alle Anderen haben keine Berechtigungen. +

|rw-
|r--
|r--
|644
|Lesbar für alle Benutzer, nicht schreibbar für andere Benutzer und nicht ausführbar für Benutzer der eigenen Gruppe.

|rw-
|r--
|---
|640
|Der Dateibesitzer kann lesen und schreiben, die Gruppe nur schreiben und alle übrigen Benutzer haben keinen Zugriff.

|rw-
|---
|r--
|604
|Lesbar für alle Benutzer, nicht schreibbar für andere Benutzer und nicht ausführbar für Benutzer der eigenen Gruppe.

|rw-
|---
|rw-
|606
|Lesbar für alle Benutzer, nicht schreibbar für andere Benutzer und nicht ausführbar Benutzer der eigenen Gruppe.

|rw-
|---
|---
|600
|Der Dateibesitzer kann lesen und schreiben, alle übrigen Benutzer haben keinen Zugriff.

|r--
|---
|---
|400
|Der Dateibesitzer kann lesen, alle übrigen Benutzer haben keinen Zugriff.
|===
