---
categories          : [Neue Kommandos für das Terminal]
description         : 'Das Programm `tree` zeigt die Verzeichnishierarchie rekursiv als Baumstruktur an. `tree` bereitet die Verzweigung der Verzeichnisse optisch auf und unterscheidet sich damit stark von ls, welches einfach nur die Inhalte von Verzeichnissen aufgelist.'
---
= Tree  Mehr Übersicht über Ordner und Dateien

[.lead]
Das Programm `tree` zeigt die Verzeichnishierarchie rekursiv als Baumstruktur an. `tree` bereitet die Verzweigung der Verzeichnisse optisch auf und unterscheidet sich damit stark von ls, welches einfach nur die Inhalte von Verzeichnissen aufgelist.


== `tree` installieren mit HomeBrew

-----
$ brew install tree
-----


== `tree` richtig nutzen

In my case, I only needed to list the first directory level with an alphanumerical file sort and utf-8 character encoding for my file output. The command for that is the following: tree -v -L 1 — charset utf-8. With the additional argument, -o backup.txt you can save the whole tree output in a file. You can also save the tree output bash-like with > backup.txt instead of using -o backup.txt.

If you’re using a daily, weekly, monthly or other scheduled backup, you need to make the backup file more unique. A sexy way is to use a date-time expression in a combination with the output file name. Here’s my final tree command which I use for my weekly backups:

-----
$ tree -v -L 1 --charset utf-8 > ordner-inhalt-$(date +%Y-%m-%d).txt
-----
